<a href="https://colab.research.google.com/github/CaioDev-one/CaioDev-one/blob/main/PostGre.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Instalando Bibliotecas

In [2]:
!pip install sqlalchemy pymysql #Mysql
!pip install sqlalchemy psycopg #Postgre

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.13/dist-packages (2.1.1)
Collecting pymysql
  Downloading pymysql-1.2.3-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.13/dist-packages (from sqlalchemy) (4.16.0)
Downloading pymysql-1.2.3-py3-none-any.whl (46 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.7/46.7 kB 2.0 MB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.2.3
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.13/dist-packages (2.1.1)
Collecting psycopg
  Downloading psycopg-3.3.6-py3-none-any.whl.metadata (4.4 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.13/dist-packages (from sqlalchemy) (4.16.0)
Downloading psycopg-3.3.6-py3-none-any.whl (215 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 215.5/215.5 kB 4.9 MB/s eta 0:00:00
Installing collected packages: psycopg
Successfully installed psycopg-3.3.6

In [7]:
import pandas as pd
from sqlalchemy import create_engine
from getpass import getpass

In [8]:
senha = getpass("Senha:")
endpoint = getpass("Endpoint:")

Senha:··········
Endpoint:··········

In [11]:
url = f"postgresql+psycopg://postgres:{senha}@{endpoint}:5432/postgres"
print(url)

postgresql+psycopg://postgres:Admin123!@database-2.clxfzcimcgol.us-east-1.rds.amazonaws.com:5432/postgres

In [12]:
engine = create_engine(url)

In [13]:
with engine.begin() as conexao:
  print("Conectado ao banco de dados")

Conectado ao banco de dados

In [21]:
tabela = {
    "sensor" : ["S01","S02","S03"],
    "setor" : ["Montagem","Usinagem","Pintura"],
    "leituras" : [72.5,81.3,32.6]

} #Criando um ".csv"

dados = pd.DataFrame(tabela)
dados.head()

  sensor     setor  leituras
0    S01  Montagem      72.5
1    S02  Usinagem      81.3
2    S03   Pintura      32.6

In [22]:
dados.to_sql("sensores",
             engine,
             if_exists="replace",
             index=False)

-1

In [23]:
teste = pd.read_sql("SELECT * FROM sensores",engine)
teste.head()

  sensor     setor  leituras
0    S01  Montagem      72.5
1    S02  Usinagem      81.3
2    S03   Pintura      32.6